spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/accessmap}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:accessmap123}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080
